core/controllers/blog.py
import datetime

import flask
from flask_login import current_user
from flask_principal import Permission, UserNeed
from sqlalchemy import text, func

from ..models import db, tags, User, Post, Comment, Tag
from ..forms import CommentForm, PostForm
from ..extensions import poster_permission, admin_permission
from ..extensions import login_required


bp_blog = flask.Blueprint(
    'blog',
    __name__,
    template_folder=('../templates/blog'),
    url_prefix='/blog'
)


def sidebar_data():
    recent = Post.query.order_by(
        Post.publish_dt.desc()
    ).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
    ).join(
        tags
    ).group_by(Tag).order_by(text('total DESC')).limit(5).all()

    return recent, top_tags


@bp_blog.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        new_post = Post(form.title.data)
        new_post.text = form.text.data
        new_post.publish_dt = datetime.datetime.now()
        new_post.user_id = current_user.get_id()

        db.session.add(new_post)
        db.session.commit()

        return flask.redirect(flask.url_for('.post', post_id=new_post.id))

    return flask.render_template('new.html', form=form)


@bp_blog.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@poster_permission.require(http_exception=403)
def edit_post(id):
    post = Post.query.get_or_404(id)
    if current_user != post.user:
        flask.abort(403)

    permission = Permission(UserNeed(post.user.id))
    if permission.can() or admin_permission.can():
        form = PostForm()

        if form.validate_on_submit():
            post.title = form.title.data
            post.text = form.text.data
            post.publish_dt = datetime.datetime.now()

            db.session.add(post)
            db.session.commit()

            return flask.redirect(flask.url_for('.post', post_id=post.id))

        form.text.data = post.text
        return flask.render_template('edit.html', form=form, post=post)
    else:
        flask.abort(403)


@bp_blog.route('/')
@bp_blog.route('/<int:page>')
def home(page=1):
    posts = Post.query.order_by(
        Post.publish_dt.desc()
    ).paginate(page, 10)
    recent, top_tags = sidebar_data()

    return flask.render_template(
        'home.html',
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@bp_blog.route('/post/<int:post_id>', methods=['GET', 'POST'])
@bp_blog.route('/post/<int:post_id>/<int:page>', methods=['GET', 'POST'])
def post(post_id, page=1):
    form = CommentForm()

    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        new_comment.dt = datetime.datetime.now()

        db.session.add(new_comment)
        db.session.commit()

        return flask.redirect(str(post_id))

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.dt.desc()).paginate(page, 10)
    recent, top_tags = sidebar_data()

    return flask.render_template(
        'post.html',
        post=post,
        tags=tags,
        comments=comments,
        recent=recent,
        top_tags=top_tags,
        form=form
    )


@bp_blog.route('/tag/<tag_name>')
@bp_blog.route('/tag/<tag_name>/<int:page>')
def tag(tag_name, page=1):
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_dt.desc()).paginate(page, 10)
    recent, top_tags = sidebar_data()

    return flask.render_template(
        'tag.html',
        tag=tag,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@bp_blog.route('/user/<username>')
@bp_blog.route('/user/<username>/<int:page>')
def user(username, page=1):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_dt.desc()).paginate(page, 10)
    recent, top_tags = sidebar_data()

    return flask.render_template(
        'user.html',
        user=user,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


# @bp_blog.before_request
# def check_user():
#     if 'username' in flask.session:
#         g.current_user = User.query.filter_by(
#             username=flask.session['username']
#         ).one()
#     else:
#         g.current_user = None

core/controllers/main.py
import json

import flask
from flask_login import login_user, logout_user, current_user
from flask_principal import Identity, AnonymousIdentity, identity_changed

from ..models import db, User
from ..extensions import oid, admin_permission
# from ..extensions import facebook
from ..forms import LoginForm, RegisterForm, OpenIDForm


bp_main = flask.Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@bp_main.route('/')
def index():
    return flask.redirect(flask.url_for('blog.home'))


@bp_main.route('/login', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    form = LoginForm()
    openid_form = OpenIDForm()

    if openid_form.validate_on_submit():
        return oid.try_login(
            openid_form.openid.data,
            ask_for=['nickname', 'email'],
            ask_for_optional=['fullname']
        )

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one()
        login_user(user, remember=form.remember.data)

        identity_changed.send(
            flask.current_app._get_current_object(),
            identity=Identity(user.id)
        )

        kwargs = {}
        if 'ldf' in flask.session:
            next_view = flask.session['ldf']['name']
            kwargs = flask.session['ldf']['kwargs']
            flask.session.pop('ldf', None)
        else:
            next_view = 'home'

        flask.flash('You have been logged in.', category='success')
        return flask.redirect(flask.url_for('blog.' + next_view, **kwargs))

    openid_errors = oid.fetch_error()
    if openid_errors:
        flask.flash(openid_errors, category='danger')

    return flask.render_template(
        'login.html',
        form=form,
        openid_form=openid_form
    )


@bp_main.route('/logout', methods=['GET', 'POST'])
def logout():
    if current_user.is_active:
        logout_user()

        identity_changed.send(
            flask.current_app._get_current_object(),
            identity=AnonymousIdentity()
        )

        flask.flash('You have been logged out.', category='success')

    return flask.redirect(flask.url_for('blog.home'))


@bp_main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        new_user = User(username=form.username.data)
        new_user.set_password(form.password.data)
        # new_user.roles = ['']
        db.session.add(new_user)
        db.session.commit()

        flask.flash(
            'Your user has been created, please log in.',
            category='success'
        )

        return flask.redirect(flask.url_for('.login'))
    else:
        return flask.render_template('register.html', form=form)


@bp_main.route('/current_user', methods=['GET'])
@admin_permission.require(http_exception=403)
def who_is_current_user():
    cu_dict = {}
    for item in dir(current_user):
        cu_dict[str(item)] = str(getattr(current_user, str(item)))
    return flask.jsonify(cu_dict)


@bp_main.route('/flask_session', methods=['GET'])
@admin_permission.require(http_exception=403)
def flask_session_info():
    fs_dict = {}
    for item in dir(flask.session):
        fs_dict[str(item)] = str(getattr(flask.session, str(item)))
    return flask.jsonify(fs_dict)


# @bp_main.route('/facebook')
# def facebook_login():
#     return facebook.authorize(
#         callback=flask.url_for(
#             '.facebook_authorized',
#             next=flask.request.referrer or None,
#             _external=True
#         )
#     )
#
#
# @bp_main.route('/facebook/authorized')
# def facebook_authorized(resp):
#     if resp is None:
#         reason = flask.request.args['error_reason']
#         error = flask.request.args['error_description']
#         return f'Access denied: reason={reason} error={error}'
#
#     flask.session['facebook_oauth_token'] = (resp['access_token'], '')
#
#     me = facebook.get('/me')
#     fname = me.data['first_name']
#     lname = me.data['last_name']
#     user = User.query.filter_by(username=fname + ' ' + lname).first()
#     if not user:
#         user = User(fname + ' ' + lname)
#         db.session.add(user)
#         db.session.commt()
#
#     flask.flash('You have been logged in', category='success')
#
#     return flask.redirect(
#         flask.request.args.get('next') or flask.url_for('blog_home')
#     )

core/templates/blog/base.html
{% macro render_pagination(pagination, endpoint) %}
  {% if pagination.pages > 1 %}
    <nav class="mt-4">
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="{{ url_for(endpoint, page=1, **kwargs) }}">First</a>
        </li>
        <li class="page-item {% if pagination.page == 1 %}disabled{% endif %}">
          <a class="page-link" href="{{ url_for(endpoint, page=pagination.prev().page, **kwargs) }}">&laquo;</a>
        </li>

        {% if pagination.page >=3 %}
          <li class="page-item {% if pagination.page >= 4 %}disabled{% endif %}">
            <a class="page-link" href="{{ url_for(endpoint, page=1, **kwargs) }}">
              {% if pagination.page == 3 %}1{% else %}...{% endif %}
            </a>
          </li>
        {% endif %}
        {% if (pagination.pages >=4) and (pagination.page >= pagination.pages - 1) %}
          <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=pagination.pages - 3, **kwargs) }}">{{ pagination.pages - 3 }}</a>
          </li>
        {% endif %}
        {% if (pagination.pages >=5) and (pagination.page == pagination.pages) %}
          <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=pagination.pages - 2, **kwargs) }}">{{ pagination.pages - 2 }}</a>
          </li>
        {% endif %}

        {% for page in pagination.iter_pages(left_edge=0, left_current=1, right_current=2, right_edge=0) %}
          {% if page %}
            <li class="page-item {% if page == pagination.page %}active{% endif %}">
              <a class="page-link" href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a>
            </li>
          {% endif %}
        {% endfor %}

        {% if (pagination.pages >= 3) and (pagination.page == 1) %}
          <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=3, **kwargs) }}">3</a>
          </li>
        {% endif %}
        {% if (pagination.pages >= 4) and (pagination.page <= 2) %}
          <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=4, **kwargs) }}">4</a>
          </li>
        {% endif %}
        {% if (pagination.pages >= 5) and (pagination.page <= pagination.pages - 2) %}
          <li class="page-item {% if pagination.page < pagination.pages - 2 %}disabled{% endif %}">
            <a class="page-link" href="{{ url_for(endpoint, page=pagination.pages, **kwargs) }}">
              {% if pagination.page < pagination.pages - 2 %}...{% else %}{{ pagination.pages }}{% endif %}
            </a>
          </li>
        {% endif %}

        <li class="page-item {% if pagination.page == pagination.pages %}disabled{% endif %}">
          <a class="page-link" href="{{ url_for(endpoint, page=pagination.next().page, **kwargs) }}">&raquo;</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{{ url_for(endpoint, page=pagination.pages, **kwargs) }}">Last</a>
        </li>
      </ul>
    </nav>
  {% endif %}
{% endmacro %}

{% macro render_form(endpoint, button_text) %}
  <form method="POST" action="{{ url_for(endpoint, **kwargs) }}">
    {{ form.hidden_tag() }}
    {% for attr in form %}
      {% if ( ('CSRF' not in attr.label | string) and ('Remember' not in attr.label | string) ) %}
        <div class="form-group">
          {% if attr.errors %}
            {% for e in attr.errors %}
              <p class="form-text">{{ e }}</p>
            {% endfor %}
          {% endif %}
          <span>{{ attr.label }}</span>
          {% if 'text' in attr.label | string %}
            {{ attr(id='editor', class_='form-control') }}
          {% else %}
            {{ attr(class_='form-control') }}
          {% endif %}
        </div>
      {% endif %}
      {% if 'Remember' in attr.label | string %}
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="RememberMe">
          <label class="form-check-label" form="RememberMe">Remember Me</label>
        </div>
      {% endif %}
    {% endfor %}
    <input class="btn btn-primary mt-3" type="submit" value="{{ button_text }}">
    {% if 'login' in endpoint %}
      <a class="btn btn-primary mt-3" href="{{ url_for('main.register') }}">Sign up</a>
    {% endif %}
  </form>
{% endmacro %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/favicon-16x16.png') }}" sizes="16x16">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/favicon-32x32.png') }}" sizes="32x32">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/favicon-96x96.png') }}" sizes="96x96">
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='icons/older-iPhone.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='icons/iPhone-6-Plus.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='icons/iPad-Retina.png') }}">
    <link rel="apple-touch-icon" sizes="167x167" href="{{ url_for('static', filename='icons/iPad-Pro.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <h1><a href="{{ url_for('blog.home') }}">Blog App</a></h1>
        <p class="font-monospace fw-bold">Welcome to the blog!</p>
      </div>
      <div class="btn-toolbar mb-3" role="toolbar">
        <div class="btn-group me-2" role="group">
          <a href="{{ url_for('blog.home') }}" class="btn btn-outline-primary" role="button">Home</a>
          <a href="#" class="btn btn-outline-primary disabled" role="button">API</a>
        </div>
        <div class="btn-group me-2" role="group">
          <a href="{{ url_for('blog.new_post') }}" class="btn btn-primary" role="button">Create a new post</a>
        </div>
        <div class="btn-group" role="group">
          {% if current_user.is_authenticated %}
            <a href="{{ url_for('blog.user', username=current_user.username) }}" class="btn btn-outline-primary" role="button">Your profile</a>
          {% endif %}
          {% if not current_user.is_authenticated %}
            <a href="{{ url_for('main.login') }}" class="btn btn-outline-primary" role="button">Login</a>
          {% else %}
            <a href="{{ url_for('main.logout') }}" class="btn btn-outline-primary" role="button">Logout</a>
          {% endif %}
        </div>
      </div>
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissable fade show" role="alert">
              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {% block body %}
      {% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

core/templates/blog/edit.html
{% extends 'base.html' %}
{% block title %}Edit post{% endblock %}
{% block body %}
  <div class="row p-2 shadow rounded mb-3">
    <h1 class="text-center">Edit post</h1>
    {{ render_form('.edit_post', 'Submit', id=post.id) }}
  </div>
{% endblock %}
{% block js %}
  <script src="https://cdn.ckeditor.com/ckeditor5/25.0.0/classic/ckeditor.js"></script>
  <script>
    ClassicEditor
      .create(document.querySelector('#editor'))
      .then(editor => {
        console.log(editor);
      }).catch(error => {
        console.error(error);
      });
  </script>
{% endblock %}

core/templates/blog/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
  <div class="row gx-5">
    <div class="col-9">
      {% for post in posts.items %}
        <div class="row p-2 shadow bg-body rounded mb-2">
            <h4>{{ post.title }}</h4>
            <span>
              {{ post.text | truncate(255) | safe }}
              <a href="{{ url_for('.post', post_id=post.id) }}">...more</a>
            </span>
        </div>
      {% endfor %}
      {{ render_pagination(posts, '.home') }}
    </div>
    <div class="col-3">
      <div class="row p-2 bg-body rounded shadow mb-2 ps-3">
        <h4>Recent Posts</h4>
        <ul class="ms-3">
          {% for post in recent %}
            <li>
              <a class="text-decoration-none" href="{{ url_for('.post', post_id=post.id) }}">{{ post.title }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
      <div class="row p-2 bg-body rounded shadow mb-2 ps-3">
        <h4>Popular Tags</h4>
        <ul class="ms-3">
          {% for tag in top_tags %}
            <li>
              <a class="text-decoration-none" href="{{ url_for('.tag', tag_name=tag[0].title) }}">{{ tag[0].title }}&nbsp;({{ tag[1] }})</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

core/templates/blog/new.html
{% extends 'base.html' %}
{% block title %}Create a new post{% endblock %}
{% block body %}
  <div class="row p-2 shadow rounded mb-3">
    <h1 class="text-center">Create a new post</h1>
    {{ render_form('.new_post', 'Submit') }}
  </div>
{% endblock %}
{% block js %}
  <script src="https://cdn.ckeditor.com/ckeditor5/25.0.0/classic/ckeditor.js"></script>
  <script>
    ClassicEditor
      .create(document.querySelector('#editor'))
      .then(editor => {
        console.log(editor);
      }).catch(error => {
        console.error(error);
      });
  </script>
{% endblock %}

core/templates/blog/post.html
{% extends 'base.html' %}
{% block title %}Post: {{ post.title }}{% endblock %}
{% block body %}
  <div class="row p-2 shadow rounded mb-3">
    <h4>{{ post.title }}</h4>
    <span>{{ post.text | truncate(255) | safe }}</span>
  </div>
  <div class="row">
    <p>
      Written by
      <a class="fw-bold text-decoration-none" href="{{ url_for('.user', username=post.user.username) }}">
        {{ post.user.username }}
      </a>
      on {{ post.publish_dt | datetimeformat }}
    </p>
    <p>
      Tags:
      {% for tag in post.tags %}
        <a class="text-decoration-none" href="{{ url_for('.tag', tag_name=tag.title) }}">{{ tag.title }}</a>
        {%- if not loop.last %},{% endif %}
      {% endfor %}
    </p>
  </div>
  {% if current_user == post.user %}
    <div class="row-sm mb-3">
      <a href="{{ url_for('.edit_post', id=post.id) }}" class="btn btn-primary" role="button">
        Edit post
      </a>
    </div>
  {% endif %}
  <div class="row p-2 shadow rounded mb-4">
    <h4>New comment:</h4>
    {{ render_form('.post', 'Add comment', post_id=post.id) }}
  </div>
  {% for comment in comments.items %}
    <div class="row shadow-none p-3 mb-3 bg-light rounded">
      <p>By: {{ comment.name }} on {{ comment.dt | datetimeformat }}</p>
      <p>{{ comment.text | truncate(255) | safe }}</p>
    </div>
  {% endfor %}
  {{ render_pagination(comments, '.post', post_id=post.id) }}
  {% endblock %}

core/templates/blog/tag.html
{% extends 'base.html' %}
{% block title %}Tag: {{ tag.title }}{% endblock %}
{% block body %}
  <div class="row">
    <h4>Posts by tag: &laquo;{{ tag.title }}&raquo;</h4>
    <hr>
  </div>
  <div class="col">
    {% for post in posts.items %}
      <div class="row p-2 shadow bg-body rounded mb-2">
          <h4>{{ post.title }}</h4>
          <span>
            {{ post.text | truncate(255) | safe }}
            <a href="{{ url_for('.post', post_id=post.id) }}">...more</a>
          </span>
      </div>
    {% endfor %}
    {{ render_pagination(posts, '.home') }}
  </div>
{% endblock %}

core/templates/blog/user.html
{% extends 'base.html' %}
{% block title %}User: {{ user.username }}{% endblock %}
{% block body %}
  <div class="row">
    <h4>Posts by author: {{ user.username }}</h4>
    <hr>
  </div>
  <div class="col">
    {% for post in posts.items %}
      <div class="row p-2 shadow bg-body rounded mb-2">
          <h4>{{ post.title }}</h4>
          <span>
            {{ post.text | truncate(255) | safe }}
            <a href="{{ url_for('.post', post_id=post.id) }}">...more</a>
          </span>
      </div>
    {% endfor %}
    {{ render_pagination(posts, '.home') }}
  </div>
{% endblock %}